Feature/hackers-news
majishanred/hackernews pull request #2
Opened 2024-07-17 12:00 UTC by majishanred

2024-07-19 07:46 UTC, myaak requested changes
Давай на стакблитз посмотрим этот `Hacker News`, уберем `React Query` и захендлим ошибки и лоадинги сами 😄 . От мемо здесь можно и избавиться, проблем возникнуть не должно

2024-07-19 07:46 UTC, myaak commented on src/utils/utils.ts
> +};
Можно написать через flatMap или .flat для вложенных

2024-07-19 07:46 UTC, myaak commented on src/pages/NewsPage.tsx
> +  }, [newsId, queryClient]);
На сколько я знаю задания нужно без квери или swr делать. На обычном аксиос, чтобы самому захендлить ошибки и научиться этим заниматься. Передеываем на `axios` 😢

2024-07-19 07:46 UTC, myaak commented on src/components/Commentary.tsx
> +export const Commentary = memo(function WrappedCommentary({ commentId }: CommentaryProps) {
Я против мемо тут, что мемоизируем? Компонент рендерится если зарендерился родитель. Норм все.
Иначе мы можем получить старый коммент.

Почему тут function? все в одном стиле пишем, всегда стрелки кидаем

2024-07-19 07:46 UTC, myaak commented on src/App.tsx
> +      <Divider></Divider>
Одиночный тег

2024-07-19 07:46 UTC, myaak commented on src/components/Commentary.tsx
> +      {comment.comments.length > 0 && <Divider />}
Да, тут будет 0 если написать `comment.comments.length && ...`, но можно написать `!!comment.comments.length`

2024-07-19 07:46 UTC, myaak commented on src/components/CommentaryBlock.tsx
> +    </>
Фрагмент тут не нужен, `return array.map`

2024-07-19 07:46 UTC, myaak commented on src/components/News.tsx
> +  const { title, url, user, time, comments_count } = data;
Я бы все равно выше до инста ретурна написал это.

2024-07-19 07:46 UTC, myaak commented on src/components/News.tsx
> +    );
Корректно ли то что ты пишешь !data это загрузка. Ведь у тебя может просто свалиться запрос. Ошибки не вижу.

Просто пока дата Undefined она может и вообще не прийти

2024-07-19 07:46 UTC, myaak commented on src/components/NewsRefetcher.tsx
> +  const newsId = useLocation().pathname.slice(1);
Ты же его из URL берешь.

По факту роутер умный, если опишешь ему `<Route path=".../:newsId" />`, то сможешь у роутера есть функция чтобы достать slug

2024-07-19 07:46 UTC, myaak commented on src/components/NewsRefetcher.tsx
> +      comments_count: data.comments_count,
Почему не сделал spread?

2024-07-19 07:46 UTC, myaak commented on src/hooks/useFetchNewsFeed.ts
> +const queryPages = [1, 2, 3, 4];
А если страниц будет больше 10? Странная логика. Нужен стейт для таких вещей + у каждой пагинации можно определить последняя это совсем страница или нет

2024-07-19 07:46 UTC, myaak commented on src/stores/slices/NewsDetailsSlice.ts
> +    [id: number]: StoredCommentary;
Скорее id - string, если ты это сделал неким словарем. У объекта ключ строчный по факту.

Для прям словаря можно использовать тип `Record<K,V>`.

Можно и мапу собрать, потому что странно, вроде `comments`, а объект

2024-07-19 07:46 UTC, myaak commented on src/stores/slices/NewsDetailsSlice.ts
> +        }
По факту тут нет смысла от `else`, ведь ты выше `return` выкинул

2024-07-19 07:46 UTC, myaak commented on src/stores/slices/NewsDetailsSlice.ts
> +      if (JSON.stringify(state.newsDetails) === JSON.stringify(action.payload)) return;
Два раза такие вещи используешь, можно в утилитарную функцию вынести

2024-07-19 07:46 UTC, myaak commented on src/types/FeedItem.ts
> +    domain?: string;
Не совсем понимаю смысла в отдельном файле для одного типа. Тип по факту компоненту пренадлежит и за его пределами используется только в сторе. Я бы прям с компонента экспортил.

Но давай так оставим, просто плодить кучу файлов на один тип - имхо странно

2024-07-19 07:46 UTC, myaak commented on src/utils/utils.ts
> +  const currentDate = new Date(date * 1000); // Походу считает не в милисекундах, а в секундах
Комменты в коде обычно оставляем
`// @NOTE: message`.
Обычно даже на строчку выше чем чет написано

2024-07-19 07:46 UTC, myaak commented on src/styled/StyledCommentaryBlock.tsx
> +    box-sizing: border-box;
Это вообще должно быть в CssReset по умолчанию на все элементы

2024-07-19 07:48 UTC, IvanKoigerov commented on src/App.tsx
> +      <Divider></Divider>
Если есть тег в который мы не передаем children, то пишем одинарный тег, самозакрывающийся, чтобы выглядело краше)

2024-07-19 07:55 UTC, IvanKoigerov commented on src/hooks/useFetchNewsFeed.ts
> +const queryPages = [1, 2, 3, 4];
В задании 100 нужно послежних отображать, так что если он не хочет делать динамическую загрузку данных, то давай так оставим

2024-07-19 08:05 UTC, myaak commented
![image](https://github.com/user-attachments/assets/2456a3ac-f3a5-4957-9c73-86d14c18ec82)
Стакблитз я не работает, какая-то проблема, нужно порешать

2024-07-22 01:59 UTC, majishanred commented on src/components/News.tsx
> +    );
Сейчас должно быть адекватно, так как я добавил обработку ошибки, потому что впихнуть как-то в стор надо дефолтное значение новости, в голову пришло только такое решение.

2024-07-22 01:59 UTC, majishanred commented on src/components/NewsRefetcher.tsx
> +      comments_count: data.comments_count,
Из-за спреда в этот объект попадают ненужные поля, по типу comments и так далее.

2024-07-22 02:19 UTC, majishanred commented
Дэн, я хз в чем проблема, Стакблитз запускается, но приложение почему-то только минуты через 3 отрисовывается.

2024-07-22 21:32 UTC, myaak requested changes

2024-07-22 21:32 UTC, myaak commented on src/components/Commentary.tsx
> +            </Box>
обертка лишняя, имхо. Тебе никто не запрещает обычному FC дать key, его не нужно определять как проп

2024-07-22 21:32 UTC, myaak commented on src/components/NewsRefetcher.tsx
> +const NewsFetcher = (newsId: string) => {
это функция, мы используем `camelCase`
Это больше уже на хук смахивает. с неймингом `useNewsFetcher`

2024-07-22 21:32 UTC, myaak commented on src/pages/NewsPage.tsx
> +      dispatch(resetStore());
Не понял идеи вообще, имхо лишнее

2024-07-22 21:32 UTC, myaak commented on src/stores/slices/NewsDetailsSlice.ts
> +  firstLevelComments: [],
Мне кажется стоит просто пустить рекурсию по `children` и все

2024-07-22 21:32 UTC, myaak commented on src/components/NewsRefetcher.tsx
> +          dispatch(setError(error.toJSON()));
по факту у axiosError вроде `message` есть, зачем toJSON, он и так сериализованный в форме объекта будет

2024-07-22 21:32 UTC, myaak commented on src/components/NewsRefetcher.tsx
> +      controller.abort();
Ты спокойно можешь не выносить везде `controller` из хука своего. Заюзай try catch и там и тут, если ты хочешь все ошибки отлавливать. Но по факту ошибка только на фетче тут будет

2024-07-22 21:32 UTC, myaak commented on src/stores/slices/NewsFeedSlice.ts
> +      }
Не думаю что стоит сидеть сравнивать что было раньше и что сейчас, ты отрендеришь эти элемеенты не так дорого, насколько дорогая может быть проверка

2024-07-22 21:32 UTC, myaak commented on src/utils/utils.ts
> +export const isShallowlyEquals = <T>(item1: T | null | undefined, item2: T | null | undefined) => {
нет смысла сранивать дальше, если у тебя один `null | undefined`, а другой не он.
Есть смысл сделать `instant return`

2024-07-22 21:32 UTC, myaak commented on src/components/NewsFeedRefetcher.tsx
> +        if (promiseResult.status === 'rejected') throw new Error('Error loading news, please reload page');
Оно у тебя выкинет ошибку в рантайме, зачем тогда `allSettled`, заюзай у тебя есть метод у `Promise`, который свалится если хоть один не зарезолвился

2024-07-22 21:32 UTC, myaak commented on src/components/News.tsx
> +        Грузим данные новости
Нужно нормальный лоадер намутить, крутилку какую-то. Не только тут

2024-07-22 21:32 UTC, myaak commented on src/components/CommentaryBlock.tsx
> +    </Box>
Как-будто излишний контейнер

2024-07-22 21:32 UTC, myaak commented on src/components/NewsFeed.tsx
> +            <Typography variant="body1">Грузим новости</Typography>
Лоадер

2024-07-22 21:32 UTC, myaak commented on src/components/NewsFeedElement.tsx
>  };
У тебя вроде файлик с типами для этой штуки есть. Как-будто туда и вынести этот тип

2024-07-22 21:32 UTC, myaak commented on src/stores/slices/NewsDetailsSlice.ts
> +      if (isShallowlyEquals<NewsDetails>(state.newsDetails, action.payload)) return;
ререндер скорее всего будет дешевле

2024-07-23 16:21 UTC, majishanred commented on src/pages/NewsPage.tsx
> +      dispatch(resetStore());
Тут из-за использования редукса, получается такая тема, что когда переходишь на страницу новой новости, где-то секунды полторы видно старую новость, но щас подумаю как пофиксить.

2024-07-23 16:53 UTC, majishanred commented on src/components/NewsRefetcher.tsx
> +          dispatch(setError(error.toJSON()));
![image](https://github.com/user-attachments/assets/a2fb9443-5af2-4372-b186-3d6e7b0f3887)

2024-07-23 16:54 UTC, majishanred commented on src/components/NewsRefetcher.tsx
> +          dispatch(setError(error.toJSON()));
Эт если просто объект засунуть туда, а если JSON все норм, но могу пихать и месседж

2024-07-23 17:54 UTC, majishanred commented on src/components/NewsFeedElement.tsx
>  };
Так мы вроде пропсы держим у компонентов?

2024-07-23 18:33 UTC, myaak commented on src/components/NewsFeedElement.tsx
>  };
Ваще не всегда, если появляется у компонента свой файл с константами или типами, то все переезжает туда

2024-07-25 12:11 UTC, myaak requested changes

2024-07-25 12:11 UTC, myaak commented on src/App.css
> +  border: none;
не вижу тут `box-sizing`, это в дефолтный ресет входит

2024-07-25 12:11 UTC, myaak commented on src/styled/StyledSpinningLoop.tsx
> +    animation-timing-function: cubic-bezier(0.18, 1.01, 0.88, 0.15); //cubic-bezier(0.2, 0.88, 0.68, 0.19);
это что комментарий?

2024-07-25 12:11 UTC, myaak commented on src/styled/StyledAnimatedLoader.tsx
> +  animation-timing-function: cubic-bezier(0.18, 1.01, 0.88, 0.15); //cubic-bezier(0.2, 0.88, 0.68, 0.19);
И тут

2024-07-26 15:14 UTC, myaak commented on src/components/Commentary.tsx
> +      if (element) element.innerHTML = comment.content;
Ваще тут главное учесть уязвимость `code injection`

По факту ты вставляешь в html все что там лежит в контенте, это сильно не безопасно
я могу спокойной вставить `<scrpt>your script</scrpit>` и чет вызвать. Хакинг все дела.

Есть библы для этого. Я пользовался DOMPurify

2024-07-26 15:15 UTC, myaak approved these changes

2024-07-26 15:15 UTC, myaak commented
@IvanKoigerov

2024-07-29 02:19 UTC, IvanKoigerov reviewed
В следующий раз мейн оставляй пустой пж, чтобы в пре были все изменения и нововедения

2024-07-29 02:19 UTC, IvanKoigerov commented on src/App.css
> +  color: #5a98f2;
В глобальных стилях не корректно менять цвет чего либо

2024-07-29 02:19 UTC, IvanKoigerov commented on src/App.css
> +}
тоже не хотелось бы это видеть в глобальном конфиге, а по месту

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/Commentary.tsx
> +        {expanded && comment.comments.map((elem) => <Commentary key={elem.id} comment={elem} />)}
если ты будешь постоянно кликать на кнопку открытия и закрытия, ты будешь постоянно моунтить и анмаунтить дочерние компоненты, это куча минус производительности
Представь, что их у тебя 100, и что по итогу будет, по одному клику юзер будет удалять и создавать 100 элементов на странице, как-то это не круто

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/News.tsx
> +  if (!newsId) throw 'News id must be provided';
как ты себе представляешь попадения юзера без id в этот компонент или ты думаешь так отловить некорректно использование твоего компонента? мне кажется бессмысленно

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/News.tsx
> +  const data = useSelector<StoresState, NewsDetails | null>((state) => state.newsStore.newsDetails);
не круто именовать таким образом твои данные, которые ты используешь. не понятно что это за data то такая,  какая это сущность

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/News.tsx
> +  if (!data) return <Loader />;
у тебя может не быть data по множеству причин, не хотелось бы чтобы ты в этот момент обязательно отображал лоудер. 
Также при нажатии на кнопку обновить, ты должен отображать юзеру, что да ты обновляешь данные, а в данном случае ты этого не сделаешь

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/News.tsx
> +          </span>
а есть ли смысл отображать эту строчку юзеру, если у него нет этой информации
Также не совсем круто на внешние ссылки редиректить юзера прям на твоей странице, так он уйдет с твоего сервиса, а это не круто и может быть неудобно, так что эту ссылку нужно открывать в новой вкладке

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/News.tsx
Что это страница или нет? Компонент еденичный или нет, не совсем понятно из твоего названия

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/NewsFeed.tsx
> +  const error = useSelector<StoresState, unknown>((state) => state.newsFeedStore.error);
Есть лучше решения для этого, можно описать свой хук, который будет возвращать корректный тип без указания значения с твоей стороны

2024-07-29 02:19 UTC, IvanKoigerov commented on src/components/NewsFeed.tsx
> +      <StyledFab onClick={() => dispatch(triggerRefetch())} sx={{ marginTop: '4px', marginLeft: 'auto' }}>
Не хотелось бы ререндерить кнопку, но раз это просто кнопка то ладно

2024-07-29 02:19 UTC, IvanKoigerov commented on src/utils/utils.ts
> +};
потрогай лучше библиотеку date fns
А ещё обычно такие функции выносят в отдельный файл как и та что ниже, нет смысла их держать в одном файле, тк служат они совершенно для разных вещей

2024-07-29 02:19 UTC, IvanKoigerov commented on src/utils/utils.ts
> +};
не совсем понимаю зачем тебе вообще это нужно

2024-07-29 02:19 UTC, IvanKoigerov commented on src/utils/utils.ts
> +};
ес и это будет в даже сильно лучше

2024-07-29 02:19 UTC, IvanKoigerov commented on src/styled/StyledHeaders.tsx
> +`;
а variant ты не используешь почему? в чем смысл?

2024-07-29 02:19 UTC, IvanKoigerov commented on src/styled/StyledFab.tsx
> +  background-color: #ffffff;
хотелось бы видеть в теме

2024-07-29 02:19 UTC, IvanKoigerov commented on src/styled/StyledCommentaryBlock.tsx
> +  padding: 8px 16px;
раз используешь mui, то давай для отступов использовать theme.spacing

2024-07-29 02:19 UTC, IvanKoigerov commented on src/styled/StyledCommentaryBlock.tsx
Странно как-то выкидывать стайледы далеко от места где ты их используешь, не вижу смысла это далеко куда-то уносить

2024-07-29 02:19 UTC, IvanKoigerov commented on src/stores/Store.ts
> +});
Не люболю когда export default привязан к каким-то значениям или описанию кода, лучше это отдельной строчкой описать

2024-07-29 02:19 UTC, IvanKoigerov commented on src/pages/NewsPage.tsx
> +      dispatch(resetStore());
лоудер тебе зачем?)

2024-07-29 02:19 UTC, IvanKoigerov commented on src/pages/NewsPage.tsx
> +    );
если сетишь ошибку в ноль, то что произойдет со страницей?

2024-07-29 02:19 UTC, IvanKoigerov commented on src/pages/NewsFeedPage.tsx
> +  }, [dispatch]);
зачем?

2024-07-29 02:19 UTC, IvanKoigerov commented on src/pages/NewsFeedPage.tsx
> +  }, [dispatch]);
ты удаляешь уже существующие новости, а если запрос не изменит значений старых и вернет те же новости, зачем тебе лишний рендер

2024-07-29 02:19 UTC, IvanKoigerov commented on src/hooks/useFetchNews.tsx
News это всегда множественное значение, меня жесть как это путает, лучше всего использовать какое-то слово, которое говорит что это сущность в единственном числе, например тот же item

2024-07-29 02:19 UTC, IvanKoigerov commented on src/hooks/useFetchNews.tsx
> +    const intervalId = setInterval(fetchNews, 1000 * 60);
если выносим в хук интервал, то мы не знаем кто захочет и как его использовать, поэтому хотелось бы, чтобы время резапроса была настраиваемой

2024-07-29 02:19 UTC, IvanKoigerov commented on src/hooks/useFetchNews.tsx
> +  const isRefetching = useSelector<StoresState, number>((state) => state.newsStore.refetchTrigger);
is - это значение всегда boolean, не юзай is  с другими типами, это сбивает

2024-07-29 02:19 UTC, IvanKoigerov commented on src/hooks/useFetchFeed.tsx
> +        );
тебе нет смысла пересоздавать эту функцию каждый раз, как и в другом хуке, будто бы лучше это вынести их тела хука

2024-07-29 02:19 UTC, IvanKoigerov commented on src/hooks/useFetchFeed.tsx
> +  const refetching = useSelector<StoresState, number>((state) => state.newsFeedStore.refetchTrigger);
в двух местах по разному сущность называешь для refetchTrigger, почему вообще ее ренеймишь, я не особо понимаю

2024-08-01 06:00 UTC, majishanred commented on src/components/News.tsx
> +  if (!newsId) throw 'News id must be provided';
Ден говорил, что ставить ! для того, чтобы сказать тсу что это значение есть - плохой тон и используется редко. Поэтому я сделал так, тс теперь не ругается и если кто-то захочет использовать компонент в месте где нет айдишника то получит ошибку.

2024-08-01 06:05 UTC, majishanred commented on src/components/Commentary.tsx
> +        {expanded && comment.comments.map((elem) => <Commentary key={elem.id} comment={elem} />)}
Не очень понял, компонент просто получает в стейт true по клику на него и отображает дочек, повторный клик по нему ничего не делает. Это как в вк, когда нажал показать больше коментов и они просто рисуются.

2024-08-01 06:12 UTC, majishanred commented on src/utils/utils.ts
> +};
Артефакт с предыдущих иттераций пра, из кода убрал а из утилок забыл.

2024-08-01 06:13 UTC, majishanred commented on src/hooks/useFetchFeed.tsx
> +  const refetching = useSelector<StoresState, number>((state) => state.newsFeedStore.refetchTrigger);
Косяк моей внимательности(

2024-08-01 06:25 UTC, majishanred commented on src/components/News.tsx
> +  if (!data) return <Loader />;
я вообще рассуждал так, есть данные - то все тип-топ значит ререндерим, если данных нет, то это их загрузка, а если че-то отвалилось во время загрузки, то это то, что должнен перехватить трай кетч. по каким еще причинам в данном контексте могут отсутствовать данные кроме как их загрузка я хз.

2024-08-01 07:42 UTC, majishanred commented
> В следующий раз мейн оставляй пустой пж, чтобы в пре были все изменения и нововедения

Сорян, думал что настройку преттиера и линтера в мейне делаем.

2024-08-01 09:33 UTC, majishanred commented on src/stores/Store.ts
> +});
А с чем это связано?

2024-08-01 09:40 UTC, majishanred commented on src/pages/NewsPage.tsx
> +    );
По идее должна была свалиться в рефетч, теперь нормально работает

2024-08-01 09:42 UTC, majishanred commented on src/styled/StyledHeaders.tsx
> +`;
На самом деле смысла не было. я прост смотрел как эта штука работает.

2024-08-01 09:58 UTC, majishanred commented on src/styled/StyledCommentaryBlock.tsx
ну тут кучка переиспользуемых есть

2024-08-12 12:12 UTC, IvanKoigerov commented on src/components/Commentary.tsx
> +        {expanded && comment.comments.map((elem) => <Commentary key={elem.id} comment={elem} />)}
ААААА ну если ты не модешь их закрыть то норм

2024-08-12 12:12 UTC, IvanKoigerov commented on src/components/ItemDetails.tsx
> +};
Что за try catch в компоненте, нее такое мы не пишем, не надо дядя

2024-08-12 12:12 UTC, IvanKoigerov commented on src/components/ItemDetails.tsx
> +      </>
Не нужен тебе тут фрагмент

2024-08-12 12:12 UTC, IvanKoigerov commented on src/components/Loader.tsx
> +  margin: ${({ theme }) => theme.spacing(2, 'auto')};
давай флексом выравнивать а не margin

2024-08-12 12:12 UTC, IvanKoigerov commented on src/pages/ItemPage.tsx
> +  if (isLoading) return <Loader />;
я разве не писал, что лоадинг так делать не круто, ты так убиваешь всю структуру

2024-08-12 12:12 UTC, IvanKoigerov commented on src/pages/ItemPage.tsx
> +      <Box marginTop="4px" paddingX="4px" display="flex" alignItems="space-between">
там сокращенная тема есть mt px
но так как тут больше 3х параметров значит выносим в стайлед

2024-08-20 14:15 UTC, merged